name: 'Test'
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_PROJECT_NAME: ${{ github.event.repository.name }}
      BROWSERSTACK_BUILD_NAME: ${{ github.ref_name }}
      BROWSERSTACK_BUILD_IDENTIFIER: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Configure NodeJS
        uses:
          actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Add hosts file entry
        run: echo "127.0.0.1 bs-local.com" | sudo tee -a /etc/hosts > /dev/null
      - name: Add virtual host
        run: |
          sudo tee /etc/apache2/sites-enabled/100-actions.conf > /dev/null << VHOST
          <VirtualHost *:80>
            ServerName bs-local.com
            DocumentRoot ${{ github.workspace }}
            <Directory ${{ github.workspace }}>
              AllowOverride All
              Order allow,deny
              Allow from all
              Require all granted
            </Directory>
          </VirtualHost>
          VHOST
      - name: Allow webserver to access workspace
        run: sudo chgrp www-data /home/$USER
      - name: Restart apache
        run: sudo service apache2 restart
      - name: Build assets
        run: npm run build
      - name: Execute tests
        run: npm run test-browserstack
