name: 'Test'
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_PROJECT_NAME: ${{ github.event.repository.name }}
      BROWSERSTACK_BUILD_NAME: ${{ github.ref_name }}
      BROWSERSTACK_BUILD_IDENTIFIER: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Configure NodeJS
        uses:
          actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      - name: Install dependencies
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Execute tests
        run: npm run test-browserstack
